doctrine:
    dbal:
        default_connection: loop
        connections:
            loop:
                dbname: '%env(resolve:DB_DATABASE)%'
                host: '%env(resolve:DB_HOST)%'
                port: 3306
                user: '%env(resolve:DB_USERNAME)%'
                password: '%env(resolve:DB_PASSWORD)%'
                driver: pdo_mysql
                server_version: '12.1'
    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: vehicle
        entity_managers:
            vehicle:
                mappings:
                    Vehicle:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Vehicle/src/Infrastructure/Persistence/Doctrine/ORM'
                        prefix: Loop\Vehicle\Model
