FROM php:8.1-fpm-alpine

WORKDIR /app

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apk update && apk add --no-cache \
    pcre-dev ${PHPIZE_DEPS} \
    && MAKEFLAGS="-j $(nproc)" pecl install pcov \
    && docker-php-ext-enable pcov \
    && apk del pcre-dev ${PHPIZE_DEPS}

RUN docker-php-ext-install pdo_mysql opcache

ENV USER=docker
ENV UID=1000
ENV GROUP=docker
ENV GID=1000

RUN addgroup --gid $GID $GROUP
RUN adduser --disabled-password --gecos '' -u $UID -G $GROUP $USER

EXPOSE 9000
